spring:
  mail:
    host: smtp.163.com
    username: javastudywxh@163.com
    password: ALGOIFARYJGGBZOV
  datasource:
    url: jdbc:mysql://localhost:3306/jpa? serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher